name: Deploy Production

on:
  push:
    branches: 
     - production

jobs:
  build_and_deploy_to_production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.3.0
        with:
          channel: beta
      - name: Enable flutter web
        run: flutter config --enable-web
      - name: Build deps
        run: flutter pub get
      ##  We don't need this as of now but we will probably later
      # - name: Build generated code
      #   run: flutter pub run build_runner build
      - name: Build web
        run: flutter build web
      - name: Deploy to prod
        uses: w9jds/firebase-action@v1.3.0
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}